### ISSUE TITLE
ERROR: No matching distribution found for opencv-python==4.1.2.30

### ISSUE THREAD

**Issue by My12123** [qweasdd/manga-colorization#2]
![2023-04-10_14-05-41](https://user-images.githubusercontent.com/49092250/230890245-79a55f98-f451-4336-ba5d-554f826e12da.png)

**Comment by Keiser04** [comment]
use the 4.8 somthing

**Comment by My12123** [comment]
Thanks for the advice, but I won't be able to test its operability ability.

**Comment by Keiser04** [comment]
is that the big problem is in the training. you train there is a problem with the file dataset.py which is supposed to create the files in bw but it does not and the training does not go. if you solved that tell me how pls.

**Comment by My12123** [comment]
@Keiser04 
It worked for me, but now I can't reproduce it, I had an error with 
```python
Traceback (most recent call last):
  File "train.py", line 294, in <module>
    torch.save(colorizer.generator.state_dict(),str(whatever_for_a_checkpoint_filename))
NameError: name 'whatever_for_a_checkpoint_filename' is not defined
``` 
Add folders to the dataset 
![2023-10-24_16-13-47](https://github.com/qweasdd/manga-colorization/assets/49092250/c3392695-dcc8-4d86-bc89-ef7b5b9698eb)
If it works, can you share the version?

**Comment by Keiser04** [comment]
@My12123 what is eval?
